### ISSUE TITLE
Change Navbar -> NavbarSimple

### ISSUE THREAD

**Issue by tcbegley** [villoro/expensor_personal#1] opened 2019-01-08 10:43 UTC
Hi @villoro

Thanks for using *dash-bootstrap-components*! I just wanted to let you know that we made a breaking change to the `Navbar` component, so if you update to version `0.3.0` or later of *dash-bootstrap-components* you might get unexpected behaviour. 

You can use the new `NavbarSimple` component exactly as you are currently using `Navbar` currently, so the easiest fix would be to just change `Navbar` to `NavbarSimple`.

Check out [the docs for `Navbar`](https://dash-bootstrap-components.opensource.asidatascience.com/l/components/navbar) and [our examples](https://github.com/ASIDataScience/dash-bootstrap-components/blob/master/examples/advanced-component-usage/Navbars.py) for more details.

**Comment by villoro** [comment] 2019-01-12 10:03
Hello @tcbegley 

I really apprecieate that you let me know about those changes.  It is also nice to have `NavbarSimple` for people that don't have time to switch. But since you implemented `Navbar` I though of giving it a chance.

At the end I like it more since it is easier to add whatever you want inside the navbar (like the logo). The only problem I found is with the `DropdownMenu` parameter `nav=True` which resulted in a weird looking navbar.

Thanks for the heads up!

**Comment by tcbegley** [comment] 2019-01-12 11:54
No problem :-)

I will take a look at the `DropdownMenu` issue you mentioned. If you have a code snippet that demonstrates the problem you describe that will be helpful, but I'll also try to reproduce it myself.

**Comment by villoro** [comment] 2019-01-12 17:09
In fact is inside a `NavBar` component (but not in a `Nav` which I am not sure what it is).

I just opened an issue in your repo with a reproducible example so that you can test it you. If this is the expected behavior feel free to close the issue I just opened.

I agree that getting rid of the `nav=True` makes the dropdown match the other buttons but I was pointing this out since I would want to use the 'naked' dropdown in future projects.

**Comment by tcbegley** [comment] 2019-01-12 18:34
Thanks! I replied on the other issue, see that for full details. In brief, I don't think it's a bug but I'll do some work to clarify the documentation / examples.

Feel free to close this issue now if you like.

**Closed** 2019-01-28 20:11 UTC
